// <auto-generated />
using GolfDay.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GolfDay.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260328000000_AddCourseTeeBoxes")]
    partial class AddCourseTeeBoxes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Intentionally minimal — EF Core only needs [DbContext] + [Migration]
            // attributes on this file to discover and apply the migration.
        }
    }
}
